const express = require('express')
const app = express()
const cors = require('cors')
const MongoClient = require('mongodb').MongoClient
const uri = process.env.MONGODB_URI


require('dotenv').config()

let db,
    dbConnectionString = process.env.DB_STRING,
    dbName = 'genshin-impact',
    collection

MongoClient.connect(dbConnectionString)
    .then(client => {
        console.log('Connected to Database')
        db = client.db(dbName)
        collection = db.collection('characters')
    })

app.set('view engine', 'ejs')
app.use(express.static('public'))
app.use(express.urlencoded({extended:true}))
app.use(express.json())
app.use(cors())

const character = {
    'albedo': {
        'name': 'Albedo',
        'title': 'Kreideprinz',
        'birthday': 'September 13th',
        'region': 'Mondstadt',
        'rarity': '5⭐',
        'element': 'Geo',
        'weapon': 'Sword',        
    },
    'aloy': {
        'name': 'Aloy',
        'title': 'Savior From Another World',
        'birthday': 'April 4th',
        'region': 'unknown',
        'rarity': '5⭐',
        'element': 'Cryo',
        'weapon': 'Bow',        
    },
    'amber': {
        'name': 'Amber',
        'title': 'Gliding Champion',
        'birthday': 'August 10th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Pyro',
        'weapon': 'Bow',        
    },
    'ayaka': {
        'name': 'Kamisato Ayaka',
        'title': 'Frostflake Heron',
        'birthday': 'September 28th',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Cryo',
        'weapon': 'Sword',        
    },
    'ayato': {
        'name': 'Kamisato Ayato',
        'title': 'Pillar of Fortitude',
        'birthday': 'March 26th',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Hydro',
        'weapon': 'Sword',        
    },
    'barbara': {
        'name': 'Barbara',
        'fullname': 'Barbara Pegg',
        'title': 'Shining Idol',
        'birthday': 'July 5th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Hydro',
        'weapon': 'Catalyst',        
    },
    'beidou': {
        'name': 'Beidou',
        'title': 'Uncrowned Lord of the Ocean',
        'birthday': 'February 14th',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Electro',
        'weapon': 'Claymore',        
    },
    'bennett': {
        'name': 'Bennett',
        'title': 'Trial by Fire',
        'rarity': '4⭐',
        'element': 'Pyro',
        'weapon': 'Sword',        
    },
    'chongyun': {
        'name': ' Chongyun',
        'title': 'Frozen Ardor',
        'birthday': 'September 7th',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Cryo',
        'weapon': 'Claymore',        
    },
    'diluc': {
        'name': 'Diluc',
        'fullname': 'Diluc Ragnvindr',
        'title': 'The Dark Side of Dawn',
        'birthday': 'April 30th',
        'region': 'Mondstadt',
        'rarity': '5⭐',
        'element': 'Pyro',
        'weapon': 'Claymore',        
    },
    'diona': {
        'name': 'Diona',
        'fullname': 'Diona Kätzlein',
        'title': 'Kätzlein Cocktail',
        'birthday': 'January 18th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Cryo',
        'weapon': 'Bow',        
    },
    'eula': {
        'name': 'Eula',
        'fullname': 'Eula Lawrence',
        'title': 'Dance of the Shimmering Wave',
        'birthday': 'October 25th',
        'region': 'Mondstadt',
        'rarity': '5⭐',
        'element': 'Cryo',
        'weapon': 'Claymore',        
    },
    'fischl': {
        'name': 'Fischl',
        'fullname': 'Fischl von Luftschloss Narfidort',
        'realname': 'Amy',
        'title': 'Prinzessin der Verurteilung',
        'birthday': 'May 27th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Electro',
        'weapon': 'Bow',        
    },
    'ganyu': {
        'rarity': '5⭐',
        'title': 'Plenilune Gaze',
        'birthday': 'December 2nd',
        'region': 'Liyue',
        'element': 'Cryo',
        'weapon': 'Bow',        
    },
    'gorou': {
        'name': 'Gorou',
        'title': 'Canine Warrior',
        'birthday': 'May 18th',
        'region': 'Inazuma',
        'rarity': '4⭐',
        'element': 'Geo',
        'weapon': 'Bow',        
    },
    'hu tao': {
        'name': 'Hu Tao',
        'title': 'Fragrance in Thaw',
        'birthday': 'July 15th',
        'region': 'Liyue',
        'rarity': '5⭐',
        'element': 'Pyro',
        'weapon': 'Polearm',        
    },
    'itto': {
        'name': 'Itto',
        'fullname': 'Arataki Itto',
        'title': 'Hanamizaka Heroics',
        'birthday': 'June 1st',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Geo',
        'weapon': 'Claymore',        
    },
    'jean': {
        'name': 'Jean',
        'fullname': 'Jean Gunnhildr',
        'title': 'Dandelion Knight',
        'birthday': 'March 14th',
        'region': 'Mondstadt',
        'rarity': '5⭐',
        'element': 'Anemo',
        'weapon': 'Sword',        
    },
    'kaeya': {
        'name': 'Kaeya',
        'fullname': 'Kaeya Alberich',
        'title': 'Frostwind Swordsman',
        'birthday': 'November 30th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Cryo',
        'weapon': 'Sword',        
    },
    'kazuha': {
        'name': 'Kazuha',
        'fullname': 'Kaedehara Kazuha',
        'title': 'Scarlet Leaves Pursue Wild Waves',
        'birthday': 'October 29th',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Anemo',
        'weapon': 'Sword',        
    },
    'keqing': {
        'name': 'Keqing',
        'title': 'Driving Thunder',
        'birthday': 'November 20th',
        'region': 'Liyue',
        'rarity': '5⭐',
        'element': 'Electro',
        'weapon': 'Sword',        
    },
    'klee': {
        'name': 'Klee',
        'title': 'Fleeing Sunlight',
        'birthday': 'July 27th',
        'region': 'Mondstadt',
        'rarity': '5⭐',
        'element': 'Pyro',
        'weapon': 'Catalyst',        
    },
    'kokomi': {
        'name': 'Kokomi',
        'fullname': 'Sangonomiya Kokomi',
        'title': 'Pearl of Wisdom',
        'birthday': 'February 22nd',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Hydro',
        'weapon': 'Catalyst',        
    },    
    'lisa': {
        'name': 'Lisa',
        'fullname': 'Lisa Minci',
        'title': 'Witch of Purple Rose',
        'birthday': 'June 9th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Electro',
        'weapon': 'Catalyst',        
    },
    'mona': {
        'name': 'Mona',
        'fullname': 'Astrologist Mona Megistus',
        'title': 'Astral Reflection',
        'birthday': 'August 31st',
        'region': 'Mondstadt',
        'rarity': '5⭐',
        'element': 'Hydro',
        'weapon': 'Catalyst',        
    },
    'ningguang': {
        'name': 'Ningguang',
        'title': 'Eclipsing Star',
        'birthday': 'August 26th',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Geo',
        'weapon': 'Catalyst',        
    },
    'noelle': {
        'name': 'Noelle',
        'title': 'Chivalric Blossom',
        'birthday': 'March 21st',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Geo',
        'weapon': 'Claymore',        
    },
    'qiqi': {
        'name': 'Qiqi',
        'title': 'Icy Resurrection',
        'birthday': 'March 3rd',
        'region': 'Liyue',
        'rarity': '5⭐',
        'element': 'Cryo',
        'weapon': 'Sword',        
    },
    'raiden': {
        'name': 'Raiden Shogun',
        'realname': 'Raiden Ei',
        'title': 'Plane of Euthymia',
        'birthday': 'June 26th',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Electro',
        'weapon': 'Polearm',        
    },
    'razor': {
        'name': 'Razor',
        'title': 'Wolf Boy',
        'birthday': 'September 9th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Electro',
        'weapon': 'Claymore',        
    },
    'rosaria': {
        'name': 'Rosaria',
        'title': 'Thorny Benevolence',
        'birthday': 'January 24th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Cryo',
        'weapon': 'Polearm',        
    },
    'sara': {
        'name': 'Kujou Sara',
        'title': 'Crowfeather Kaburaya',
        'birthday': 'July 14th',
        'region': 'Inazuma',
        'rarity': '4⭐',
        'element': 'Electro',
        'weapon': 'Bow',        
    },
    'sayu': {
        'name': 'Sayu',
        'title': 'Mujina Ninja',
        'birthday': 'October 19th',
        'region': 'Inazuma',
        'rarity': '4⭐',
        'element': 'Anemo',
        'weapon': 'Claymore',        
    },
    'shenhe': {
        'name': 'Shenhe',
        'title': 'Lonesome Transcendence',
        'birthday': 'March 10th',
        'region': 'Liyue',
        'rarity': '5⭐',
        'element': 'Cryo',
        'weapon': 'Polearm',        
    },
    'sucrose': {
        'name': 'Sucrose',
        'title': 'Harmless Sweetie',
        'birthday': 'November 26th',
        'region': 'Mondstadt',
        'rarity': '4⭐',
        'element': 'Anemo',
        'weapon': 'catalyst',        
    },
    'tartaglia': {
        'name': 'Tartaglia',
        'title': 'Childe',
        'birthday': 'July 20th',
        'region': 'Snezhnaya',
        'rarity': '5⭐',
        'element': 'Hydro',
        'weapon': 'Bow',        
    },
    'thoma': {
        'name': 'Thoma',
        'title': 'Protector From Afar',
        'birthday': 'January 9th',
        'region': 'Inazuma',
        'rarity': '4⭐',
        'element': 'Pyro',
        'weapon': 'Polearm',        
    },
    'traveler': {
        'name': {
            'female': 'Lumine',
            'male': 'Aether'
        },
        'title': 'Outlander',
        'birthday': 'unknown',
        'region': 'unknown',
        'rarity': '5⭐',
        'element': ['Anemo', 'Geo', 'Electro'],
        'weapon': 'Sword',        
    },
    'venti': {
        'name': 'Venti',
        'title': 'Windborne Bard',
        'birthday': 'June 16th',
        'region': 'Mondstadt',
        'rarity': '5⭐',
        'element': 'Anemo',
        'weapon': 'Bow',        
    },
    'xiangling': {
        'name': 'Xiangling',
        'fullname': 'Mao Xiangling',
        'title': 'Exquisite Delicacy',
        'birthday': 'November 2nd',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Pyro',
        'weapon': 'Polearm',        
    },
    'xiao': {
        'name': 'Xiao',
        'title': 'Vigilant Yaksha',
        'birthday': 'April 17th',
        'region': 'Liyue',
        'rarity': '5⭐',
        'element': 'Anemo',
        'weapon': 'Polearm',        
    },
    'xingqiu': {
        'name': 'Xingqiu',
        'title': 'Juvenile Galant',
        'birthday': 'October 9th',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Hydro',
        'weapon': 'Sword',        
    },
    'xinyan': {
        'name': 'Xinyan',
        'title': 'Blazing Riff',
        'birthday': 'October 16th',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Pyro',
        'weapon': 'Claymore',        
    },
    'yae miko': {
        'name': 'Yae Miko',
        'title': 'Astute Amusement',
        'birthday': 'June 27th',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Electro',
        'weapon': 'Catalyst',        
    },
    'yanfei': {
        'name': 'Yanfei',
        'title': 'Wise Innocence',
        'birthday': 'July 28th',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Pyro',
        'weapon': 'Catalyst',        
    },
    'yelan': {
        'name': 'Yelan',
        'title': 'Valley Orchid',
        'birthday': 'April 20th',
        'region': 'Liyue',
        'rarity': '5⭐',
        'element': 'Hydro',
        'weapon': 'Bow',        
    },
    'yoimiya': {
        'name': 'Yoimiya',
        'fullname': 'Naganohara Yoimiya',
        'title': 'Frolicking Flames',
        'birthday': 'June 21st',
        'region': 'Inazuma',
        'rarity': '5⭐',
        'element': 'Pyro',
        'weapon': 'Bow',        
    },
    'yun jin': {
        'name': 'Yun Jin',
        'title': 'Stage Lucida',
        'birthday': 'May 21st',
        'region': 'Liyue',
        'rarity': '4⭐',
        'element': 'Geo',
        'weapon': 'Polearm',        
    },
    'zhongli': {
        'name': 'Zhongli',
        'title': 'Vago Mundo',
        'birthday': 'December 31st',
        'region': 'Liyue',
        'rarity': '5⭐',
        'element': 'Geo',
        'weapon': 'Polearm',        
    },
    'unknown': {
        'name': 'unknown'
    }
}


app.get('/', (request, response) => {
    response.sendFile(__dirname + '/index.html')
})

app.get('/api/:characterName', (request, response) => {
    const characterName = request.params.name.toLowerCase()
        infoCollection.find({name: characterName}).toArray()
        .then(results => {
            console.log(results)
            response.json(results[0])
        })
        .catch(error => console.error(error))
})

app.listen(process.env.PORT || PORT, () => {
    console.log(`Server is running.`)
})


